In [ ]:
import numpy as np

def train_test_split_manual(X, y, test_size, shuffle=True, random_state=None):

    X = np.array(X)
    y = np.array(y)
          
    n_samples = len(X)
    n_test = int(n_samples * test_size)
    
    indices = np.arange(n_samples)
    
    
    if shuffle:
        if random_state is not None:
            np.random.seed(random_state)
        np.random.shuffle(indices)
    
    test_indices = indices[:n_test]
    train_indices = indices[n_test:]
    
    return X[train_indices], X[test_indices], y[train_indices], y[test_indices]



In [56]:
def linear_regression(x,y ,x_test):
    X=np.array(x).flatten()
    X_test=np.array(x_test).flatten()
    y=np.array(y)

    y_mean= np.mean(y)
    X_mean= np.mean(X)
    beta_numerator=0
    beta_denominator=0
    for i in range(X.size):
        beta_numerator += (X[i]-X_mean)*(y[i]-y_mean)
        beta_denominator += (X[i]-X_mean)**2
    beta =(beta_numerator/beta_denominator)
    c= (y_mean) - beta*(X_mean)

    y_pred= beta* X_test + c
    
    return float(beta) , float(c) , y_pred
        


In [59]:
X = [[4], [9], [8], [8], [7],[5]]
y = [52, 51, 50, 52, 70 , 60 ]

X_train, X_test, y_train, y_test = train_test_split_manual(X, y, test_size=0.2, random_state=42)


b, c , y_pred = linear_regression(X_train, y_train , X_test)






error = []
for i in range(len(y_test)):
    error.append(y_test[i] - y_pred[i])
print("Test Errors:", error)

print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)


y_new = [[6],[6],[5],[9]]
y_new_pred = []
for i in range(len(y_new)):
    
    prediction = (b * y_new[i][0]) + c 
    y_new_pred.append(prediction)

print("Predictions for y_new:", y_new_pred)


[0 1 2 3 4 5]
[0 1 5 2 4 3]
Test Errors: [np.float64(-15.391304347826079)]
X_train: [[9]
 [5]
 [8]
 [7]
 [8]]
X_test: [[4]]
y_train: [51 60 50 70 52]
y_test: [52]
Predictions for y_new: [61.04347826086956, 61.04347826086956, 64.21739130434781, 51.52173913043478]


In [92]:
def multi_linear_regression(x,y ,x_test):
    X=np.array(x)
    X_test=np.array(x_test)
    y=np.array(y)

    y_mean= np.mean(y)
    X_mean= []
    r=X.shape[0]
    c=X.shape[1]
    for i in range(c):
        sum=0
        for j in range(r):
            sum+=X[j][i]
        X_mean.append(sum/r)
    beta=[]
    for i in range(c):
        beta_numerator=0
        beta_denominator=0
        for j in range(r):
            beta_numerator += (X[j][i]-X_mean[i])*(y[j]-y_mean)
            beta_denominator += (X[j][i]-X_mean[i])**2
        beta.append(beta_numerator/beta_denominator)
    const=0
    temp=0
    for i in range(c):
        temp+=beta[i]*X_mean[i]
    const=y_mean-temp

    y_pred=[]
    for r in range(X_test.shape[0]):
        temp=0
        for c in range(X_test.shape[1]):
            temp += beta[c]* X_test[r][c] 
        y_pred.append(temp+const)
    
    return list(beta) , const, list(y_pred)



In [95]:
X=[[4,1,3],[9,2 ,1],[8,3,2],[8,1,1],[7,1,4],[5,0,2]]
y = [52, 51, 50, 52, 70 , 60 ]

X_train, X_test, y_train, y_test = train_test_split_manual(X, y, test_size=0.2, random_state=42)

beta , c, y_pred=multi_linear_regression(X_train,y_train,X_test)
print(X_test)
print(beta , c, y_pred)
print()
print(np.array(y_pred))

[0 1 2 3 4 5]
[0 1 5 2 4 3]
[[4 1 3]]
[np.float64(-3.1739130434782608), np.float64(-4.269230769230768), np.float64(6.166666666666667)] 73.73054626532888 [np.float64(75.26566332218508)]

[75.26566332]


In [ ]:
class multi_linear_regression :

    def __init__(self):
        self.beta = None
        self.const = None

    def fit(self,x,y):
        r_X=np.array(x)
        y=np.array(y)

        X=np.c_[np.ones(r_X.shape[0]),r_X]
        b= np.linalg.inv((np.transpose(X) @ X)) @ (np.transpose(X) @ y)
        self.const = b[0]
        self.beta = b[1:]
        for i in range(c):
            sum=0
        for j in range(r):
            sum+=X[j][i]
        X_mean.append(sum/r)

    def predict(self,x):
        r_X=np.array(x)
        return self.const + r_X@self.beta

